/*******************************************************************************
 * M2MSHA1.h : Implementation of SHA-1 hash algorithm
 *
 * Copyright (c) 2018, Akihisa Yasuda
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/

#pragma once

#ifndef M2M_LIB_SECURITY_M2MSHA1_H_
#define M2M_LIB_SECURITY_M2MSHA1_H_



#ifdef __cplusplus
extern "C"
{
#endif /* __cplusplus */



#include <inttypes.h>
#include <stdlib.h>
#include <string.h>


/*******************************************************************************
 * Class variable
 ******************************************************************************/
/**
 * 20[Byte] means length of SHA-1 digest data.
 */
#ifndef M2MSHA1_DIGEST_LENGTH
#define M2MSHA1_DIGEST_LENGTH (uint32_t)20
#endif /* M2MSHA1_DIGEST_LENGTH */


/*******************************************************************************
 * Public function
 ******************************************************************************/
/**
 * This method generates SHA1 hash digest data generated by indicated source data.<br>
 *
 * @param[in] src		Source data
 * @param[in] srcLength	Length of source
 * @param[out] digest	SHA1 hash digest data
 * @return				Length of generated SHA-1 hash digest[Byte]
 */
uint32_t M2MSHA1_getDigest (const unsigned char *src, size_t srcLength, unsigned char digest[M2MSHA1_DIGEST_LENGTH]);



#ifdef __cplusplus
}
#endif /* __cplusplus */



#endif /* M2M_SECURITY_M2MSHA1_H_ */
