/*******************************************************************************
 * M2MSHA1.c
 *
 * Copyright (c) 2018, Akihisa Yasuda
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/

#include "m2m/lib/security/M2MSHA1.h"


/*******************************************************************************
 * Private function
 ******************************************************************************/
/**
 *  Define the SHA1 circular left shift macro
 */
#define this_M2MSHA1CircularShift( bits, word ) ( ((word) << (bits)) | ((word) >> (32-(bits))) )


/**
 * @param hash
 * @param message
 */
static void this_processMessageBlock (uint32_t *hash, unsigned char *message)
	{
	uint32_t i = 0;
	uint32_t temp;
	uint32_t W[80];
	uint32_t A, B, C, D, E;
	const uint32_t K[] = {0x5A827999, 0x6ED9EBA1, 0x8F1BBCDC, 0xCA62C1D6};

	for (i = 0; i < 16; i++)
		{
		W[i] = message[i * 4] << 24;
		W[i] |= message[i * 4 + 1] << 16;
		W[i] |= message[i * 4 + 2] << 8;
		W[i] |= message[i * 4 + 3];
		}

	for (i = 16; i < 80; i++)
		{
		W[i] = this_M2MSHA1CircularShift(1, W[i-3] ^ W[i-8] ^ W[i-14] ^ W[i-16]);
		}
	A = hash[0];
	B = hash[1];
	C = hash[2];
	D = hash[3];
	E = hash[4];

	for (i = 0; i < 20; i++)
		{
		temp =  this_M2MSHA1CircularShift(5, A) +((B & C) | ((~B) & D)) + E + W[i] + K[0];
		E = D;
		D = C;
		C = this_M2MSHA1CircularShift(30, B);
		B = A;
		A = temp;
		}

	for (i = 20; i < 40; i++)
		{
		temp = this_M2MSHA1CircularShift(5, A) + (B ^ C ^ D) + E + W[i] + K[1];
		E = D;
		D = C;
		C = this_M2MSHA1CircularShift(30, B);
		B = A;
		A = temp;
		}

	for (i = 40; i < 60; i++)
		{
		temp = this_M2MSHA1CircularShift(5, A) + ((B & C) | (B & D) | (C & D)) + E + W[i] + K[2];
		E = D;
		D = C;
		C = this_M2MSHA1CircularShift(30, B);
		B = A;
		A = temp;
		}

	for (i = 60; i < 80; i++)
		{
		temp = this_M2MSHA1CircularShift(5, A) + (B ^ C ^ D) + E + W[i] + K[3];
		E = D;
		D = C;
		C = this_M2MSHA1CircularShift(30, B);
		B = A;
		A = temp;
		}
	hash[0] += A;
	hash[1] += B;
	hash[2] += C;
	hash[3] += D;
	hash[4] += E;
	return;
	}



/*******************************************************************************
 * Public function
 ******************************************************************************/
/**
 * This method generates SHA1 hash digest data generated by indicated source data.<br>
 *
 * @param[in] src		Source data
 * @param[in] srcLength	Length of source
 * @param[out] digest	SHA1 hash digest data
 * @return				Length of generated SHA-1 hash digest[Byte]
 */
uint32_t M2MSHA1_getDigest (const unsigned char *src, size_t srcLength, unsigned char digest[M2MSHA1_DIGEST_LENGTH])
	{
	//========== Variable ==========
	uint32_t Length_Low = 0;
	uint32_t Length_High = 0;
	uint32_t index = 0;
	const uint32_t WORD = 4;
	const uint32_t BLOCK = 64;
	uint32_t hash[M2MSHA1_DIGEST_LENGTH/WORD];
	unsigned char message[BLOCK];

	//===== Initialization =====
	memset(hash, 0, sizeof(hash));
	hash[0] = 0x67452301;
	hash[1] = 0xEFCDAB89;
	hash[2] = 0x98BADCFE;
	hash[3] = 0x10325476;
	hash[4] = 0xC3D2E1F0;
	memset(message, 0, sizeof(message));

	while (srcLength--)
		{
		message[index++] = (*src & 0xFF);
		Length_Low += 8;
		if (Length_Low == 0)
			{
			Length_High++;
			}
		if (index==64)
			{
			this_processMessageBlock(hash, message);
			index = 0;
			}
		src++;
		}
	if (55<index)
		{
		message[index++] = 0x80;
		while (index<BLOCK)
			{
			message[index++] = 0;
			}
		this_processMessageBlock(hash, message);
		index = 0;
		while (index<56)
			{
			message[index++] = 0;
			}
		}
	else
		{
		message[index++] = 0x80;
		while (index<56)
			{
			message[index++] = 0;
			}
		}
	message[56] = Length_High >> 24;
	message[57] = Length_High >> 16;
	message[58] = Length_High >> 8;
	message[59] = Length_High;
	message[60] = Length_Low >> 24;
	message[61] = Length_Low >> 16;
	message[62] = Length_Low >> 8;
	message[63] = Length_Low;
	this_processMessageBlock(hash, message);

	for (index=0; index<M2MSHA1_DIGEST_LENGTH; index++)
		{
		digest[index] = hash[index>>2] >> 8 * (3 - (index & 0x03));
		}

	return M2MSHA1_DIGEST_LENGTH;
	}


/* End Of File */

